spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    org.jooq: DEBUG
    vn.backend: DEBUG

minio:
  endpoint: http://localhost:9000
  bucket: ${MINIO_BUCKET:crm}
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}

app:
  name: Base Backend
  version: 1.0.0
system:
  enabled-register: true
  domain: http://localhost:9000

jwt:
  expiration-access-token: ${EXPIRATION_AT:300000}
  expiration-refresh-token: ${EXPIRATION_RT:5184000} #60 days = 60 * 24 * 60 * 60
  secret-key-access-token: ${SECRET_KET_AT:TuAnD3pZa1Jyl3use1/ChT3uaD1PZa4V0ick+T84IABvc}
  secret-key-refresh-token: ${SECRET_KEY_RT:Ty@nDzaiHc23grw3@/Tr0NgVt23Ym+145hjgRtBn9fv6y}

stripe:
  secret-key: sk_test_51SbfhpE9IPXqNCFleiZiy6IacS6Jy41kxLMHu8CQQiJHhW0F8yTxNeog4P8hPR1ltNiLpAxx9Bw2cnNNTDfGRDab00Jxf6bmds
  webhook-secret: whsec_8wjZQUIKSk30umdeUlGmGu7zartUhCQ4
  success-url: /order-success
  cancel-url: /checkout
